### PR TITLE
Update README.md(By Changing the Name)

### PR DESCRIPTION
**Pull request by irahulcse**
Learning about the project and it's documentation for now.

### CODE REVIEW

**Comment by arpansac** [comment]
This appears interesting, but do you think we should be mentioning it since we are planning to move this to a more common name for getting in more communities?

**Comment by irahulcse** [comment]
@arpansac I am getting your point, but I want to know how the Commudle is going to work and what are things need to write in the readme, as it lacks a lot of important information which we should be written regarding the commudle.

**Comment by arpansac** [comment]
> @arpansac I am getting your point, but I want to know how the Commudle is going to work and what are things need to write in the readme, as it lacks a lot of important information which we should be written regarding the commudle.

@irahulcse Yup, that's why the issue #20 . Write now it contains forms, events, communities and users! You'll know more as soon as you set it up and make a community. 

Also, just so that we can be a little more structured from the beginning, let's refer to an issue which is being resolved while calling for a PR.

We've just gone open source for this platform which is being extensively used for our events and really appreciate your inputs :)

**Comment by arpansac** [comment]
@irahulcse let's close it for now and take the path of issue created --> assigned to you --> PR marking that issue resolved.

**Comment by irahulcse** [comment]
Ok @arpansac Fine!. Thanks Sir.

**Pull request closed without merging**
